[general]
data_dir = "./data/hsc_example/hsc_8asec_1000"

[download]
filter = ["HSC-G", "HSC-R", "HSC-I"]

[model]
name = "ExampleAutoencoder"
base_channel_size = 32
latent_dim = 64

[data_set]
name = "HSCDataset"
crop_to = [96, 96]