[general]
use_gpu = true

[download]
sw = "22asec"
sh = "22asec"
filter = ["HSC-G", "HSC-R", "HSC-I", "HSC-Z", "HSC-Y"]
type = "coadd"
rerun = "pdr3_wide"
username = "mtauraso@local"
password = "cCw+nX53lmNLHMy+JbizpH/dl4t7sxljiNm6a7k1"
max_connections = 2
fits_file = "../hscplay/temp.fits"
cutout_dir = "../hscplay/cutouts/"
offset = 0
num_sources = 10

[model]
name = "ExampleCNN"

# An example of requesting an external model class
# external_class = "user_package.submodule.ExternalModel"

weights_filepath = "example_model.pth"
epochs = 10

[data_loader]
name = "CifarDataLoader"

# An example of requesting an external data loader class
# external_class = "user_package.submodule.ExternalDataLoader"

# Directory path where the data is stored
path = "./data"

# Default PyTorch DataLoader parameters
batch_size = 4
shuffle = true
num_workers = 2

[predict]
batch_size = 32
